#!/usr/bin/ruby

if File.symlink?(__FILE__)
  $:.unshift(File.dirname(File.readlink(__FILE__))) unless $:.include?(File.dirname(File.readlink(__FILE__))) 
else
  $:.unshift(File.dirname(__FILE__)) unless $:.include?(File.dirname(__FILE__)) 
end
$:.unshift("#{File.dirname(__FILE__)}/libxml-ruby-0.8.3/ext/libxml")

require "account.rb"

begin
  if ARGV.length > 0
    name=ARGV[0]
  else
    name=`groups`.split(/\s+/)[0]
  end
  account=Account.new(name)
  account.print_params
rescue
  puts $!
end
