#!/usr/bin/ruby

if File.symlink?(__FILE__)
  $:.insert($:.size-1,File.dirname(File.readlink(__FILE__))) unless $:.include?(File.dirname(File.readlink(__FILE__)))
else
  $:.insert($:.size-1,File.dirname(__FILE__)) << File.dirname(__FILE__) unless $:.include?(File.dirname(__FILE__))
end


require "sgebatchsystem.rb"
require "getoptlong"

opts= GetoptLong.new(
  ["-s", GetoptLong::REQUIRED_ARGUMENT]
)

# Parse the options
opts.each { |option,arg|

  if option=="-s"
    ENV['SGE_ROOT']=arg
  end

}

begin
  if ENV['SGE_ROOT'].nil?
    sge_root="/usr/local/sge"
  else
    sge_root=ENV['SGE_ROOT']
  end
  SGEBatchSystem.new(sge_root).rollover if File.exists?(sge_root)
rescue
  puts $!
end






