#!/home/harrop/opt/ruby-1.8.7-p352/bin/ruby

# Get the base directory of the WFM installation
if File.symlink?(__FILE__)
  __WFMDIR__=File.dirname(File.dirname(File.expand_path(File.readlink(__FILE__),File.dirname(__FILE__))))
else
  __WFMDIR__=File.dirname(File.expand_path(File.dirname(__FILE__)))
end

# Add include paths for WFM and libxml-ruby libraries
$:.unshift("#{__WFMDIR__}/lib")
$:.unshift("#{__WFMDIR__}/lib/libxml-ruby")
$:.unshift("#{__WFMDIR__}/lib/sqlite3-ruby")
$:.unshift("#{__WFMDIR__}/lib/SystemTimer")

# Load workflow engine library

require 'drb'
require 'workflowmgr/workflowserver'

# Turn off SIGINT here because we do not want pending signals from the
# parent to shutdown the server.  The parent will catch the signal and
# shutdown the servers correctly.
Signal.trap("INT",nil)

# Start a Drb Server that will serve the workflow log object
DRb.start_service(nil,WorkflowMgr::WorkflowServer.new)

# Write the URI to /tmp so the client can connect
uri_file="#{ENV['HOME']}/.rocoto/tmp/workflowmgr_#{$$}_uri"
File.open(uri_file,"w") { |file| file.puts "#{DRb.uri}" }

# Wait forever for the server to quit
DRb.thread.join
