.\"-
.\" Manual page written by Timothy Brown <Timothy.P.Brown@noaa.org>
.\"
.\"
.Dd January 25, 2013
.Os
.Dt ROCOTOCHECK 1 CON
.Sh NAME
.Nm rocotocheck
.Nd query detailed information about specified tasks in specified cycles of a Rocoto workflow.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl v Ar #
.Op Fl -version
.Fl d Ar database_file
.Fl w Ar workflow_file
.Fl t Ar task
.Fl c Ar cycle
.Sh DESCRIPTION
.Nm
is a tool to query detailed information about a specific task for a specific
cycle of a specific Rocoto workflow.
.Pp
The rocotocheck command is particularly useful for determining why a particular 
task cannot be submitted.  Rocotocheck reports which dependencies are satisfied
and which are not, as well as any throttle violations that are preventing a 
task from being submitted.
.Pp
The
.Nm
command requires two arguments. The
.Cm -w
flag specifies the name
of the workflow definition file. The
.Cm -d
flag specifies the name of the database file
that contains the state of the workflow for the task that is to be checked.
.Pp
Additionally, the rocotocheck command will not do anything unless the -c option
and at least one of -a, -m, or -t are specified.
.Pp
The following options are available:
.Bl -tag -width flag
.It Fl -version
Display the version number and exit.
.It Fl h, -help
Display a short help message and exit.
.It Fl v, -verbose Ar #
Run Rocoto in verbose mode with the specified level. If no level is
specified a level of 1 is used.
.It Fl d, -database Ar file
The path to the Rocoto database file for the current workflow.
.It Fl w, -workflow Ar file
The path to the Rocoto workflow file.
.It Fl c, --cycle Ar cyclespec[,cyclespec[,...]]
Only check jobs for these cycles. See
.Sx WORKFLOW SUBSETTING
.It Fl m, --metatasks Ar metataskspec[,metataskspec[,...]]
Only check jobs for these metatasks.  See
.Sx WORKFLOW SUBSETTING
.It Fl t, --tasks Ar taskspec[,taskspec[,...]
Only check jobs for these tasks.  See
.Sx WORKFLOW SUBSETTING
.It Fl a, --all
Include all tasks in the workflow subset.  See
.Sx WORKFLOW SUBSETTING
.El
.Sh WORKFLOW SUBSETTING
All Rocoto commands that monitor or modify the workflow can be told to
run on some subset of that workflow.  Subset specifications use the
-a, -t, -c, and -m options.  Using multiple options adds to the
selection.  The rocotocheck program will do nothing unless you provide
at least one cyclespec (-c option) and one taskspec or metataskspec
(-a, -m, and -t options).
.Pp
The resulting set is the set union of the -t, -m, and -a option, for
each cycle selected by the -c option.

.Ss All Tasks: The -a Option
The -a option has no arguments, and selects all possible tasks.  It is
an error to specify -t or -m if the -a option is given.

.Ss Task Subset: The -t Option
This consists of one or more comma-separated lists of task
specifications which describe the set of tasks.  Without a leading
dash, every taskspec adds to the set of selected tasks (set union).
With a dash, the taskspec is removed (set subtraction) from the list
of tasks.
.Bl -tag flag
.It Ar -taskspec[,taskspec[,...]]
Negate the option (remove tasks from the selection instead of adding).
This applies to all taskspecs following the "-".
.It Ar /regex/
Include all tasks whose names match the given regular expression
(everything within the two slashes).  Typical regular expression
characters have their usual meanings: ( [ ] ) | . * +
.It Ar :attribute
Select all tasks that have the specified XML attribute set for its
<task> tag, and the attribute is true, non-zero, or non-empty.
Supported attributes are final, shared, exclusive, cores, and nodes.
The special value "metatasks" selects tasks that are in a metatask
(any metatask).
.It Ar @cycledef
Select all tasks in the given cycledef
.It Ar taskname
Select a task with the specified name.
.El

.Ss Metatask Subset: The -m Option
This consists of one or more comma-separated lists of metatask
specifications which describe the set of metatasks.  Without a leading
dash, every metataskspec adds to the set of selected metatasks (set
union).  With a dash, the metataskspec is removed (set subtraction)
from the list of metatasks.
.Bl -tag flag
.It Ar -metataskspec[,metataskspec[,...]]
Negate the option (remove metatasks from the selection instead of adding).
This applies to all metataskspecs following the "-".
.It Ar metataskname
Add a metatask to the selected tasks.
.El

.Ss Cycle subset: The -c Option
Unlike the -t and -m options, the -c option can only include one
cyclespec, rather than a comma-separated list (except individual
cycles; see below).  Every cyclespec adds to the set of selected
cyclespec (set union).  Set subtraction is NOT supported (no -
options).
.Bl -tag flag
.It Ar YYYYMMDDHHMM[,YYYYMMDDHHMM[,...]]
Select specific cycles, given their twelve-digit date/time specification.
.It Ar YYYYMMDDHHMM:YYYYMMDDHHMM
Select the specified range of cycles.
.It Ar :YYYYMMDDHHMM
Select all cycles from the first one to the given cycle.
.It Ar YYYYMMDDHHMM:
Select all cycles from the given cycle to the last known cycle.
.It Ar all | ALL
Select all cycles.
.It @cycledef
Select all cycles in the specified cycledef.
.El

.Sh EXAMPLES
The command:
.Pp
.Dl "rocotocheck -d foo.db -w foo.xml -t wrf -c 201301010000"
.Pp
Will check the
.Qq wrf
task for the cycle
.Qq 201301010000
defined in the workflow definition file named
.Qq foo.xml
and contained in the database file named
.Qq foo.db
.Sh EXIT STATUS
.Ex -std
.Sh DOCUMENTATION
Complete documentation can be found at: http://rdhpcs.noaa.gov/rocoto/
.Sh SEE ALSO
.Xr rocotoboot 1 ,
.Xr rocotocomplete 1 ,
.Xr rocotorewind 1 ,
.Xr rocotorun 1 ,
.Xr rocotostat 1
.Sh STANDARDS
The
.Nm
command is expected to be
.St -p1003.2
compatible.
.Sh AUTHOR
Written by Christopher Harrop
.Sh BUGS
Report bugs to <christopher.w.harrop@noaa.gov>
